SELECT A.ORGANIZATION_ID,
       TRANSACTION_DATE,
       A.CREATION_DATE,
       SEGMENT1                ITEM_CODE,
       TRANSACTION_TYPE_NAME,
       SUBINVENTORY_CODE,
       B.DESCRIPTION,
       TRANSACTION_QUANTITY,
       INV_ATTRIBUTE13         이전조직,
       TRANSFER_ORGANIZATION_ID,
       TRANSFER_SUBINVENTORY,
       PO_NUM,
       RELEASE_NUM,
       LINE_NUM,
       UNIT_PRICE,
       PO_UNIT_PRICE           RCV_PRICE,
       ORDER_NUMBER,
       LINE_NUMBER,
       TRANSACTIONAL_CURR_CODE CURRENCY_CODE,
       OM_ATTRIBUTE1,
       SELLING_PRICE_KRW,
       RCV_TRANSACTION_ID,
       OLA_LINE_ID
FROM XXE_MMT_TRX_DETAIL_V A
         INNER JOIN MTL_SUBINVENTORIES_ALL_V B
                    ON A.ORGANIZATION_ID = B.ORGANIZATION_ID
                        AND A.SUBINVENTORY_CODE = B.SECONDARY_INVENTORY_NAME
WHERE TRANSACTION_DATE >= TO_DATE('20201101', 'YYYYMMDD')
  AND TRANSACTION_DATE <= TO_DATE('20201211', 'YYYYMMDD')
  AND SEGMENT1 = 'G504000270'
;
